---
title: domdoes.design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dominicdelongdesigns@gmail.com
url: https://www.domdoes.design
description: Experience Design . Visual Design . Brand Identity
color:
  primary-dark: "#000000"
  links: "#24ffc2"
footer: Your Website
social:
- title: twitter
  url: https://twitter.com/SBootstrap
- title: facebook
  url: 
- title: stack-overflow
  url: http://stackoverflow.com/questions/tagged/jekyll
- title: bitbucket
  url: http://bitbucket.org/jekyll
- title: github
  url: https://github.com/IronSummitMedia/startbootstrap
markdown: kramdown
permalink: pretty
